{% set name = "aws-checksums" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c9d0100a5743765fc8034e34e2310f77f59b1adab6f2e2f2d4d2a3bd81b2a36d

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("aws-checksums", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
  host:
    - aws-c-common

outputs:
  - name: aws-checksums
    script: build-shared.sh  # [unix]
    script: bld-shared.bat  # [win]
    build:
      activate_in_script: True
      run_exports:
        - {{ pin_subpackage("aws-checksums", max_pin="x.x.x") }}
    requirements:
      build:
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - ninja
      host:
        - aws-c-common
    test:
      commands:
        - test -f $PREFIX/lib/libaws-checksums${SHLIB_EXT}  # [unix]
        - test ! -f $PREFIX/lib/libaws-checksums.a  # [unix]
        - test -f $PREFIX/include/aws/checksums/exports.h  # [unix]
        - if not exist %PREFIX%\\Library\\bin\\aws-checksums.dll exit 1  # [win]
        - if exist %PREFIX%\\Library\\lib\\aws-checksums.lib exit 1  # [win]

  - name: aws-checksums-static
    script: build-static.sh  # [unix]
    script: bld-static.bat  # [win]
    build:
      activate_in_script: True
    requirements:
      build:
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - ninja
      host:
        - aws-c-common-static
        - {{ pin_subpackage("aws-checksums", exact=True) }}
    test:
      commands:
        - test ! -f $PREFIX/lib/libaws-checksums${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libaws-checksums.a  # [unix]
        - test -f $PREFIX/include/aws/checksums/exports.h  # [unix]
        - if exist %PREFIX%\\Library\\bin\\aws-checksums.dll exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\aws-checksums.lib exit 1  # [win]
about:
  home: https://github.com/awslabs/aws-checksums
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Cross-Platform HW accelerated CRC32c and CRC32 with fallback to efficient SW implementations. C interface with language bindings for each of our SDKs.

extra:
  recipe-maintainers:
    - xhochy
    - davidbrochart
