{% set name = "aws-checksums" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 48223950e3fc654fe959947eb780f45e2751216a387b810331f8f4af724f3b1e

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-checksums", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
  host:
    - aws-c-common

test:
  commands:
    - test -f $PREFIX/lib/libaws-checksums${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/checksums/exports.h  # [unix]

about:
  home: https://github.com/awslabs/aws-checksums
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Cross-Platform HW accelerated CRC32c and CRC32 with fallback to efficient SW implementations. C interface with language bindings for each of our SDKs.

extra:
  recipe-maintainers:
    - xhochy
